/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/

CREATE TABLE EVENTS (
    ID INTEGER NOT NULL,
    GROUPID INTEGER,
    PARTICIPANTID INTEGER,
    TYPEID INTEGER,
    TEXT VARCHAR(400),
    TIME TIMESTAMP);


CREATE TABLE EVENTTYPES (
    ID INTEGER NOT NULL,
    NAME VARCHAR(20));


CREATE TABLE GROUPS (
    ID INTEGER NOT NULL,
    NAME VARCHAR(30),
    DESCRIPTION VARCHAR(500),
    OWNERID INTEGER,
    CREATIONDATE TIMESTAMP);


CREATE TABLE INVITATIONS (
    ID INTEGER NOT NULL,
    SENDERID INTEGER,
    RECIPIENTID INTEGER,
    GROUPID INTEGER);


CREATE TABLE ORDERS (
    ID INTEGER NOT NULL,
    CREATORID INTEGER,
    GROUPID INTEGER,
    PRODUCT VARCHAR(70),
    AMOUNT INTEGER,
    STATUS SMALLINT,
    EXPIRE TIMESTAMP);


CREATE TABLE PARTICIPANTS (
    GROUPID INTEGER,
    PARTICIPANTID INTEGER,
    BALANCE FLOAT);


CREATE TABLE PARTICIPATIONS (
    PURCHASEID INTEGER NOT NULL,
    PARTICIPANTID INTEGER,
    MEASURE INTEGER);


CREATE TABLE PURCHASES (
    ID INTEGER NOT NULL,
    CUSTOMERID INTEGER,
    GROUPID INTEGER,
    PRODUCT VARCHAR(70),
    PRICE FLOAT,
    AMOUNT INTEGER,
    TIME TIMESTAMP);


CREATE TABLE SESSIONS (
    TOKEN VARCHAR(100) NOT NULL,
    USERID INTEGER);


CREATE TABLE USERS (
    ID INTEGER NOT NULL,
    NAME VARCHAR(70),
    PASSWORD VARCHAR(30),
    REGISTRATION TIMESTAMP,
    LASTENTER INTEGER,
    EMAIL INTEGER);




/******************************************************************************/
/***                                 Views                                  ***/
/******************************************************************************/



/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/


ALTER TABLE EVENTS ADD CONSTRAINT HISTORY_PK PRIMARY KEY (ID);
ALTER TABLE EVENTTYPES ADD CONSTRAINT EVENTTYPES_PK PRIMARY KEY (ID);
ALTER TABLE GROUPS ADD CONSTRAINT GROUPS_PK PRIMARY KEY (ID);
ALTER TABLE INVITATIONS ADD CONSTRAINT INVITATIONS_PK PRIMARY KEY (ID);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_PK PRIMARY KEY (ID);
ALTER TABLE PARTICIPATIONS ADD CONSTRAINT PARTICIPATIONS_PK PRIMARY KEY (PURCHASEID);
ALTER TABLE PURCHASES ADD CONSTRAINT PURCHASES_PK PRIMARY KEY (ID);
ALTER TABLE SESSIONS ADD CONSTRAINT SESSIONS_PK PRIMARY KEY (TOKEN);
ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY (ID);

/******************************************************************************/
/***                           Unique constraints                           ***/
/******************************************************************************/



/******************************************************************************/
/***                              Foreign keys                              ***/
/******************************************************************************/


ALTER TABLE EVENTS ADD CONSTRAINT FK_LINKEDUSER FOREIGN KEY (PARTICIPANTID) REFERENCES USERS (ID);
ALTER TABLE EVENTS ADD CONSTRAINT FK_GROUP FOREIGN KEY (GROUPID) REFERENCES GROUPS (ID);
ALTER TABLE EVENTS ADD CONSTRAINT FK_TYPE FOREIGN KEY (TYPEID) REFERENCES EVENTTYPES (ID);
ALTER TABLE GROUPS ADD CONSTRAINT FK_OWNER FOREIGN KEY (OWNERID) REFERENCES USERS (ID);
ALTER TABLE INVITATIONS ADD CONSTRAINT FK_SENDER FOREIGN KEY (SENDERID) REFERENCES USERS (ID);
ALTER TABLE INVITATIONS ADD CONSTRAINT FK_RECIPIENT FOREIGN KEY (RECIPIENTID) REFERENCES USERS (ID);
ALTER TABLE INVITATIONS ADD CONSTRAINT FK_GROUP_INITATION FOREIGN KEY (GROUPID) REFERENCES GROUPS (ID);
ALTER TABLE ORDERS ADD CONSTRAINT FK_CREATOR FOREIGN KEY (CREATORID) REFERENCES USERS (ID);
ALTER TABLE ORDERS ADD CONSTRAINT FK_GROUP_ORDERS FOREIGN KEY (GROUPID) REFERENCES GROUPS (ID);
ALTER TABLE PARTICIPANTS ADD CONSTRAINT FK_GROUP_PARTICIPANTS FOREIGN KEY (GROUPID) REFERENCES GROUPS (ID);
ALTER TABLE PARTICIPANTS ADD CONSTRAINT FK_USERS FOREIGN KEY (PARTICIPANTID) REFERENCES USERS (ID);
ALTER TABLE PARTICIPATIONS ADD CONSTRAINT FK_PURCHASE FOREIGN KEY (PURCHASEID) REFERENCES PURCHASES (ID);
ALTER TABLE PARTICIPATIONS ADD CONSTRAINT FK_PARTICIPANT FOREIGN KEY (PARTICIPANTID) REFERENCES USERS (ID);
ALTER TABLE PURCHASES ADD CONSTRAINT FK_GROUP_PURCHASE FOREIGN KEY (GROUPID) REFERENCES GROUPS (ID);
ALTER TABLE PURCHASES ADD CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMERID) REFERENCES USERS (ID);
ALTER TABLE SESSIONS ADD CONSTRAINT FK_USER FOREIGN KEY (USERID) REFERENCES USERS (ID);
